services:
  task-manager:
    image: task-manager
    container_name: task-manager
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    env_file:
      - .env
    networks:
      - pg-network

  pg:
    image: postgres:latest
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: task-manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network


volumes:
  postgres_data:

networks:
  pg-network:
    driver: bridge
    name: pg-network
